import datetime
import json
import os

try:
    from openai import OpenAI
except ImportError:
    OpenAI = None

class ReportGenerationAgent:
    """
    Report Generation Agent (Documentation AI)
    Takes raw KPI datasets and AI insights from other agents (Pulse, Anomaly, Forecaster)
    and generates structured reports (Finance, Academic, Main KPIs).
    """
    def __init__(self, company_name="Carthage Analytics"):
        self.company_name = company_name

    def generate_executive_summary_with_openai(self, kpi_datasets):
        """
        Uses OpenAI to generate a pulse summary based on the raw KPI data.
        """
        if not OpenAI:
            return "OpenAI library not installed. Please install it using 'pip install openai'."
            
        api_key = os.environ.get("OPENAI_API_KEY")
        if not api_key:
            return "OpenAI API key not found. Please set the OPENAI_API_KEY environment variable to generate real insights."
            
        try:
            client = OpenAI(api_key=api_key)
            prompt = f"Tu es un analyste de données expert. Voici les KPIs : {json.dumps(kpi_datasets)}. Rédige un 'Pulse' (un bref point de santé de l'entreprise) en exactement 2 à 3 phrases en français qui résument les insights majeurs."
            
            response = client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[
                    {"role": "system", "content": "You are a professional business analytics AI."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=150,
                temperature=0.7
            )
            return response.choices[0].message.content.strip()
        except Exception as e:
            return f"Erreur lors de la génération avec OpenAI : {str(e)}"

    def generate_markdown_report(self, kpi_datasets, ai_insights):
        """
        Generates a comprehensive Markdown report including Finance, Academic, and Main KPIs.
        
        Args:
            kpi_datasets (dict): Raw KPI data (e.g., revenue, conversion rate).
            ai_insights (dict): Insights generated by other agents (pulse, anomalies, forecast).
            
        Returns:
            str: The formatted Markdown report.
        """
        date_str = datetime.datetime.now().strftime("%Y-%m-%d")
        
        # Extract data with defaults
        pulse = ai_insights.get("pulse_summary", "No pulse summary provided.")
        if not pulse or pulse == "auto":
            pulse = self.generate_executive_summary_with_openai(kpi_datasets)
            
        anomalies = ai_insights.get("anomalies", [])
        forecast = ai_insights.get("forecast", {})
        
        revenue = kpi_datasets.get("revenue", 0)
        target = kpi_datasets.get("target_revenue", 0)
        conversion = kpi_datasets.get("conversion_rate", 0.0)
        university_kpis = kpi_datasets.get("university_kpis", [])
        
        # Build Report Sections
        report = f"# Comprehensive Business Report - {self.company_name}\n"
        report += f"**Date:** {date_str}\n\n"
        
        # 1. Executive Summary (AI Insights)
        report += "## 1. Executive Summary (AI Pulse)\n"
        report += f"> {pulse}\n\n"
        
        # 2. Financial Section
        report += "## 2. Financial Overview\n"
        report += "| Metric | Current Value | Target | Status |\n"
        report += "|--------|---------------|--------|--------|\n"
        
        status = "✅ On Track" if revenue >= target else "⚠️ Needs Attention"
        report += f"| Gross Revenue | {revenue:,.2f} € | {target:,.2f} € | {status} |\n"
        report += "\n"
        
        # 3. Main KPIs Section
        report += "## 3. Main KPIs & Operations\n"
        report += f"- **Conversion Rate:** {conversion:.2f}%\n"
        
        if forecast:
            report += f"- **Forecasted Trend:** {forecast.get('trend_direction', 'N/A')}\n"
            report += f"- **Risk Level:** {forecast.get('risk_level', 'N/A')}\n"
            report += f"- **Next Period Prediction:** {forecast.get('predicted_values', ['N/A'])[0]:,.2f} €\n"
        report += "\n"
        
        # University Performance
        if university_kpis:
            report += "### University Performance (Success Rate)\n"
            valid_kpis = [k for k in university_kpis if "success_rate" in k]
            if valid_kpis:
                highest = max(valid_kpis, key=lambda x: x["success_rate"])
                lowest = min(valid_kpis, key=lambda x: x["success_rate"])
                
                report += f"- ✅ **Highest success rate** → {highest['university']} ({highest['success_rate']}%)\n"
                report += f"- ✅ **Lowest success rate** → {lowest['university']} ({lowest['success_rate']}%)\n\n"
        
        
        # 4. Academic & Technical Analysis Section
        report += "## 4. Academic & Statistical Analysis\n"
        report += "### Anomaly Detection (Z-Score Analysis)\n"
        if anomalies:
            report += "The following statistical anomalies were detected in the recent dataset:\n"
            for anomaly in anomalies:
                period_info = anomaly.get('period', 'N/A')
                details_info = ' '.join(anomaly.get('details', []))
                report += f"- **Period {period_info}:** {details_info}\n"
        else:
            report += "No significant statistical anomalies detected in the current period.\n"
            
        report += "\n### Forecasting Confidence (Linear Regression)\n"
        if forecast:
            report += f"The forecasting model yields an R-squared based confidence score of **{forecast.get('confidence_score_pct', 0)}%**.\n"
            report += f"Estimated trend growth rate per period: **{forecast.get('trend_growth_rate_pct', 0)}%**.\n"
            
        report += "\n---\n*Report generated automatically by Carthage AI Documentation Agent.*"
        
        return report

if __name__ == "__main__":
    # Mock data to test the report generation agent
    mock_kpi_datasets = {
        "revenue": 115000,
        "revenue_prev": 110000,
        "conversion_rate": 3.2,
        "target_revenue": 120000,
        "university_kpis": [
            {"university": "ENICarthage", "success_rate": 92},
            {"university": "IHEC", "success_rate": 85},
            {"university": "ISG", "success_rate": 78},
            {"university": "FSEG", "success_rate": 65}
        ]
    }
    
    # Mock insights simulating outputs from the Pulse, Anomaly, and Forecast agents
    mock_ai_insights = {
        "pulse_summary": "auto",  # Set to "auto" to trigger OpenAI generation
        "anomalies": [
            {
                "period": "Last Quarter",
                "details": ["Revenue (45000 €) deviates significantly from the norm (z-score > 2.0)."]
            }
        ],
        "forecast": {
            "trend_direction": "Upward",
            "trend_growth_rate_pct": 2.1,
            "risk_level": "Low",
            "confidence_score_pct": 85.5,
            "predicted_values": [118500]
        }
    }
    
    agent = ReportGenerationAgent()
    markdown_output = agent.generate_markdown_report(mock_kpi_datasets, mock_ai_insights)
    
    print("=== GENERATED REPORT PREVIEW ===\n")
    try:
        print(markdown_output)
    except UnicodeEncodeError:
        print(markdown_output.encode('cp1252', errors='replace').decode('cp1252'))
    
    # Optionally save to a file
    report_filename = "sample_report.md"
    with open(report_filename, "w", encoding="utf-8") as f:
        f.write(markdown_output)
    print(f"\n[+] Report saved to '{report_filename}'")
